apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.1.0
        profile:
            VendorType: partner
            version: v1.0
        chart-uri: /charts/vault-0.13.0.tgz
        digest: sha256:1bd53046da7f8fed779acaff89e3fda98c18f2771e7623a2a7a5d57360b3b7d5
        digests:
            chart: sha256:1bd53046da7f8fed779acaff89e3fda98c18f2771e7623a2a7a5d57360b3b7d5
            package: 9cce9e5dd3648224bd0e72e5f58d72c8472216c3d4ea9b124d88d9a09746e643
        lastCertifiedTimestamp: "2021-07-09T15:15:33.264242+00:00"
        certifiedOpenShiftVersions: 4.7.0
    chart:
        name: vault
        home: https://www.vaultproject.io
        sources:
          - https://github.com/hashicorp/vault
          - https://github.com/hashicorp/vault-helm
          - https://github.com/hashicorp/vault-k8s
          - https://github.com/hashicorp/vault-csi-provider
        version: 0.18.0
        description: Official HashiCorp Vault Chart
        keywords:
          - vault
          - security
          - encryption
          - secrets
          - management
          - automation
          - infrastructure
        maintainers: []
        icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 1.7.3
        deprecated: false
        annotations: {}
        kubeversion: '>= 1.14.0-0'
        dependencies: []
        type: ""
    chart-overrides: ""
results:
  - check: v1.0/contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: v1.0/has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: v1.0/not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: v1.0/not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: v1.0/has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: v1.0/is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: v1.0/contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: v1.0/contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: v1.0/helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: v1.0/images-are-certified
    type: Mandatory
    outcome: PASS
    reason: |-
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault-k8s:0.10.2-ubi
        Image is Red Hat certified : registry.connect.redhat.com/hashicorp/vault:1.7.3-ubi
  - check: v1.0/chart-testing
    type: Mandatory
    outcome: FAIL
    reason: Test failed check

